# Generated by Django 5.2.3 on 2025-06-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familya', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='group/')),
                ('tajriba', models.CharField(max_length=255)),
                ('mutaxasislig', models.CharField(max_length=255)),
            ],
        ),
    ]
