# Generated by Django 5.2.3 on 2025-06-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyha',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loyha',
            name='images',
            field=models.ImageField(upload_to='loyha/'),
        ),
    ]
